version: "3"
services:
  consumer:
    build: .
    volumes:
      - ./consumer:/home/app/app
  producer:
    build: .
    volumes:
      - ./producer:/home/app/app
  topic:
    image: ches/kafka
    command: "kafka-topics.sh --create --topic darksouls --replication-factor 1 --partitions 1 --zookeeper zookeeper:2181"
    depends_on:
      - zookeeper
      - kafka
  zookeeper:
    image: zookeeper:3.4
    ports:
      - "2181:2181"
  kafka:
    image: ches/kafka
    ports:
      - "9092:9092"
    environment:
      ZOOKEEPER_IP: zookeeper
